# tasks file for vagrant setup
---
- name: Install Virtualbox on MacOS
  homebrew_cask:
    name: "{{vagrant_virtualbox_version}}" 
    state: latest

- name: Install Vagrant on MacOS
  homebrew_cask:
    name: "{{vagrant_version}}" 
    #when: "{{vagrant_virtualbox_install}}"
    state: latest

- name: Initialize Vagrant
